---
name: Generate Interactive HTML BOM
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install InteractiveHtmlBom
        run: |
          sudo apt-get update
          sudo apt-get install -y kicad
          python3 -m pip install InteractiveHtmlBom
      - name: Generate Interactive HTML BOM
        run: >
          generate_interactive_bom --dest-dir . --name-format out.html door_open_alarm.kicad_pcb
      - name: Upload HTML BOM as artifact
        uses: actions/upload-artifact@v2
        with:
          name: interactive-html-bom
          path: out.html
